import React from 'react'
import { Card, CardContent } from '@/components/ui/card'
import { Badge } from '@/components/ui/badge'
import { 
  TrendingUp, 
  Clock, 
  Target, 
  Users, 
  Image as ImageIcon,
  CheckCircle,
  ArrowRight
} from 'lucide-react'
import { Button } from '@/components/ui/button'

const MarketTrends = () => {
  const marketStats = [
    {
      stat: "91%",
      description: "of businesses use visual content as a marketing tool in 2025",
      trend: "+15% from 2024",
      color: "text-green-400",
      icon: TrendingUp
    },
    {
      stat: "84%",
      description: "of consumers were convinced to buy after seeing engaging visuals",
      trend: "Higher than any other content type",
      color: "text-blue-400",
      icon: Target
    },
    {
      stat: "300%",
      description: "more leads generated by AI-powered visual content vs. traditional ads",
      trend: "ROI continues climbing",
      color: "text-purple-400",
      icon: ImageIcon
    },
    {
      stat: "65%",
      description: "of executives visit the marketer's website after viewing compelling visual content",
      trend: "B2B content effectiveness",
      color: "text-orange-400",
      icon: Users
    }
  ]

  const missedOpportunities = [
    {
      title: "Short-Form Visual Explosion",
      description: "TikTok, Instagram Reels, and YouTube Shorts are dominating. Brands not creating short-form content (images & videos) are missing 73% of Gen Z and Millennial audiences. Our SaaS platform makes it easy to keep up with a clear, user-friendly interface, showing you how to adapt content for each platform.",
      urgency: "Critical",
      timeframe: "Happening Now"
    },
    {
      title: "AI Content Revolution",
      description: "Early adopters of AI visual creation are producing 10x more content (images & videos) at 90% lower cost through efficient SaaS solutions. Late adopters will struggle to compete on volume and speed. Our UI/UX ensures you understand how to maximize these benefits, with clear dashboards for tracking your content output.",
      urgency: "High",
      timeframe: "Next 6 months"
    },
    {
      title: "Personalization at Scale",
      description: "Consumers expect personalized visual experiences. Brands using AI to create targeted image and video variants through accessible SaaS platforms see 40% higher engagement rates. Our platform provides the tools to achieve this easily, guiding you through personalization options with clear controls.",
      urgency: "Growing",
      timeframe: "This year"
    }
  ]

  const competitorAdvantages = [
    "Creating 5-10 visual assets per week while you create 1 per month",
    "Testing multiple content variations to optimize performance",
    "Responding to trends within hours, not weeks",
    "Building stronger brand presence across all platforms",
    "Capturing your potential customers with engaging visual content"
  ]

  return (
    <section className="py-20 bg-gray-900 relative overflow-hidden border-y border-primary/20">
      {/* Subtle Background Elements with Primary Theme */}
      <div className="absolute inset-0 overflow-hidden">
        <div className="absolute -top-40 right-40 w-96 h-96 bg-primary/10 rounded-full blur-3xl animate-pulse"></div>
        <div className="absolute -bottom-40 left-40 w-96 h-96 bg-accent/10 rounded-full blur-3xl animate-pulse" style={{ animationDelay: '1s' }}></div>
      </div>

      <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 relative z-10">
        {/* Header */}
        <div className="text-center mb-16">
          <Badge variant="outline" className="text-primary border-primary/30 bg-primary/10 py-2 px-4 text-sm font-semibold">
            <TrendingUp className="w-5 h-5 mr-2" />
            MARKET INSIGHTS
          </Badge>
          <h2 className="font-montserrat font-bold text-3xl md:text-4xl text-white mt-4 mb-4">
            THE AI CREATIVE REVOLUTION IS HAPPENING RIGHT NOW
            <span className="block bg-gradient-to-r from-primary to-accent text-transparent bg-clip-text">WITH SAAS INNOVATION</span>
          </h2>
          <p className="font-opensans text-xl text-gray-300 max-w-3xl mx-auto">
            The shift to AI-powered visual content is accelerating, driven by accessible SaaS platforms like ours. Forward-thinking businesses are positioning themselves now to capture the opportunity through intuitive, high-quality tools that provide clear insights and a trustworthy experience.
          </p>
        </div>

        {/* Market Statistics */}
        <div className="grid md:grid-cols-2 lg:grid-cols-4 gap-6 mb-16">
          {marketStats.map((stat, index) => {
            const Icon = stat.icon
            return (
              <Card key={index} className="bg-gray-800/50 border-gray-700 hover:border-primary/50 transition-all duration-300 hover:-translate-y-1">
                <CardContent className="p-6 text-center">
                  <Icon className={`w-8 h-8 ${stat.color} mx-auto mb-4`} />
                  <div className={`font-montserrat font-bold text-3xl ${stat.color} mb-2`}>
                    {stat.stat}
                  </div>
                  <p className="text-white text-sm mb-2 font-medium">
                    {stat.description}
                  </p>
                  <Badge variant="outline" className="text-xs text-gray-400">
                    {stat.trend}
                  </Badge>
                </CardContent>
              </Card>
            )
          })}
        </div>

        {/* Market Opportunities */}
        <div className="mb-16">
          <h3 className="font-montserrat font-bold text-2xl text-white mb-8 text-center">
            📈 Current Market Opportunities
          </h3>
          <div className="grid md:grid-cols-3 gap-6">
            {missedOpportunities.map((opportunity, index) => (
              <Card key={index} className="bg-gradient-to-br from-primary/10 to-accent/10 border border-primary/20 hover:border-primary/40 transition-all duration-300 shadow-lg hover:shadow-primary/10">
                <CardContent className="p-6">
                  <div className="flex items-center justify-between mb-4">
                    <Badge className={`${
                      opportunity.urgency === 'Critical' ? 'bg-red-500' :
                      opportunity.urgency === 'High' ? 'bg-orange-500' :
                      'bg-yellow-500'
                    } text-white`}>
                      {opportunity.urgency}
                    </Badge>
                    <span className="text-gray-400 text-sm">{opportunity.timeframe}</span>
                  </div>
                  <h4 className="font-montserrat font-bold text-white mb-3">
                    {opportunity.title}
                  </h4>
                  <p className="text-gray-300 text-sm">
                    {opportunity.description}
                  </p>
                </CardContent>
              </Card>
            ))}
          </div>
        </div>

        {/* Market Leaders */}
        <div className="bg-gray-800/40 border border-gray-700/60 rounded-2xl p-8">
          <div className="grid md:grid-cols-2 gap-8 items-center">
            <div className="space-y-4">
              <h3 className="font-montserrat font-bold text-2xl text-white">
                What Market Leaders Are Doing
                <span className="block text-primary text-lg font-normal">While Others Are Still Planning</span>
              </h3>
              {competitorAdvantages.map((advantage, index) => (
                <div key={index} className="flex items-start gap-3">
                  <CheckCircle className="w-5 h-5 text-green-400 mt-1 flex-shrink-0" />
                  <p className="text-gray-300">{advantage}</p>
                </div>
              ))}
            </div>
            <div className="bg-gradient-to-br from-primary/10 to-accent/10 border border-primary/30 rounded-xl p-6">
              <h4 className="font-montserrat font-bold text-white mb-4 flex items-center gap-2">
                <TrendingUp className="w-5 h-5 text-green-400" />
                You Can Catch Up Fast
              </h4>
              <p className="text-gray-300 mb-4">
                With AI-powered visual content creation via our SaaS platform, you can produce a month's worth of content (images & videos) in a single day. Start now and leapfrog competitors still using traditional methods, with a clear path to success and a UI/UX that makes every step understandable.
              </p>
              <Button 
                onClick={() => document.querySelector('#pricing')?.scrollIntoView({ behavior: 'smooth' })}
                className="w-full bg-gradient-to-r from-primary to-accent text-white font-semibold py-3 rounded-lg group"
              >
                Explore Pricing & Plans
                <ArrowRight className="ml-2 w-4 h-4 group-hover:translate-x-1 transition-transform" />
              </Button>
            </div>
          </div>
        </div>
      </div>
    </section>
  )
}

export default MarketTrends
